const Data = [
  {
    id: "1",
    trending: true,
    imageSrc: "/images/trend_image1.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "2",
    imageSrc: "/images/trend_image2.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "3",
    imageSrc: "/images/trend_image3.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "4",
    trending: true,
    imageSrc: "/images/trend_image4.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "5",
    imageSrc: "/images/trend_image5.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "6",
    trending: true,
    imageSrc: "/images/trend_image6.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "7",
    imageSrc: "/images/trend_image7.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    trending: true,
    discount: "-33%",
  },
  {
    id: "8",
    imageSrc: "/images/trend_image8.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    trending: true,
    discount: "-33%",
  },
];

export default Data;
