const Data = [
  {
    id: "1",
    trending: true,
    imageSrc: "/images/trend_image1.png",
    title: "MEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    color: "#34EB43",
    discount: "-33%",
  },
  {
    id: "2",
    imageSrc: "/images/trend_image2.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    color: "#EB5834",
    discount: "-33%",
  },
  {
    id: "3",
    imageSrc: "/images/trend_image3.png",
    title: "WOMEN BOTTOM",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    color: "#34A4EB",
    discount: "-33%",
  },
  {
    id: "4",
    trending: true,
    imageSrc: "/images/trend_image4.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Fu-ever Sweatshirt",
    price: "₹2000",
    color: "#EB3471",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "5",
    imageSrc: "/images/trend_image5.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Fu-ever ",
    price: "₹2000",
    color: "#EB5834",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "6",
    trending: true,
    imageSrc: "/images/trend_image6.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Cargo",
    price: "₹2000",
    color: "#EBDE34",
    priceDis: "₹1700",
    discount: "-33%",
  },
  {
    id: "7",
    imageSrc: "/images/trend_image7.png",
    title: "WOMEN SWEATSHIRT",
    subtitle: "Together Shirt",
    price: "₹2000",
    priceDis: "₹1700",
    color: "#FFFFFF",
    trending: true,
    discount: "-33%",
  },
  {
    id: "8",
    imageSrc: "/images/trend_image8.png",
    title: "MEN BOTTOM",
    subtitle: "Fu-ever Sweatshirt",
    price: "₹2000",
    priceDis: "₹1700",
    color: "#000000",
    trending: true,
    discount: "-33%",
  },
];

export default Data;
